import assert from "assert";
import * as anchor from "@project-serum/anchor";
import { Program, web3 } from "@project-serum/anchor";
import { TOKEN_PROGRAM_ID, Token } from "@solana/spl-token";
import { MarinadeReferral } from "../target/types/marinade_referral";

const { Keypair, SystemProgram, PublicKey, SYSVAR_RENT_PUBKEY } = web3;

describe("marinade-referral", () => {
    // Local cluster provider.
    const provider = anchor.Provider.env();

    // Configure the client to use the local cluster.
    anchor.setProvider(provider);

    const program = anchor.workspace
        .MarinadeReferral as Program<MarinadeReferral>;

    // referral code
    const REF_CODE = "ref0001";

    // referral state PDA
    let referralPda: InstanceType<typeof PublicKey>;
    // mSOL beneficiary vault PDA
    let beneficiaryPda: InstanceType<typeof PublicKey>;

    // mSOL token mint
    let msolMint: Token;
    // mSOL mint authority, maybe marinade main program id
    const msolMintAuthority = Keypair.generate();

    // partner account
    const partner = Keypair.generate();

    it("should initialize referral state", async () => {
        // Airdrop SOLs to the partner.
        await provider.connection.confirmTransaction(
            await provider.connection.requestAirdrop(partner.publicKey, 1e10),
            "confirmed"
        );

        // referral state PDA generated by ref code
        const [_referral_pda, _referral_bump] =
            await PublicKey.findProgramAddress(
                [
                    Buffer.from(anchor.utils.bytes.utf8.encode("referral")),
                    Buffer.from(anchor.utils.bytes.utf8.encode(REF_CODE)),
                ],
                program.programId
            );
        referralPda = _referral_pda;

        // beneficiary
        const [_beneficiary_pda, _beneficiary_bump] =
            await PublicKey.findProgramAddress(
                [
                    Buffer.from(anchor.utils.bytes.utf8.encode("beneficiary")),
                    Buffer.from(anchor.utils.bytes.utf8.encode(REF_CODE)),
                ],
                program.programId
            );
        beneficiaryPda = _beneficiary_pda;

        // create mSOL token mint
        msolMint = await Token.createMint(
            provider.connection,
            partner,
            msolMintAuthority.publicKey,
            null,
            0,
            TOKEN_PROGRAM_ID
        );

        // initialize referral PDA
        await program.rpc.initialize(
            REF_CODE,
            _referral_bump,
            _beneficiary_bump,
            {
                accounts: {
                    state: referralPda,
                    msolMint: msolMint.publicKey,
                    beneficiary: beneficiaryPda,
                    partnerAccount: partner.publicKey,
                    rent: SYSVAR_RENT_PUBKEY,
                    tokenProgram: TOKEN_PROGRAM_ID,
                    systemProgram: SystemProgram.programId,
                },
                signers: [partner],
            }
        );

        // get PDA state
        const referralState = await program.account.referralState.fetch(
            referralPda
        );
        // check if partner address matches what we expect
        assert.ok(referralState.partnerAccount.equals(partner.publicKey));

        // it should not initialize another referral PDA with the same refer code
        await assert.rejects(async () => {
            await program.rpc.initialize(
                REF_CODE,
                _referral_bump,
                _beneficiary_bump,
                {
                    accounts: {
                        state: referralPda,
                        msolMint: msolMint.publicKey,
                        beneficiary: beneficiaryPda,
                        partnerAccount: partner.publicKey,
                        rent: SYSVAR_RENT_PUBKEY,
                        tokenProgram: TOKEN_PROGRAM_ID,
                        systemProgram: SystemProgram.programId,
                    },
                    signers: [partner],
                }
            );
        });
    });

    it("should update emergency pause", async () => {
        // pause referral
        await program.rpc.pause(true, {
            accounts: {
                state: referralPda,
                partnerAccount: partner.publicKey,
            },
            signers: [partner],
        });

        // get PDA state
        const pausedReferralState = await program.account.referralState.fetch(
            referralPda
        );
        // check if paused
        assert.ok(pausedReferralState.pause === true);

        // resume referral
        await program.rpc.pause(false, {
            accounts: {
                state: referralPda,
                partnerAccount: partner.publicKey,
            },
            signers: [partner],
        });

        // get PDA state
        const referralState = await program.account.referralState.fetch(
            referralPda
        );
        // check if resumed
        assert.ok(referralState.pause === false);
    });

    it("should not update emergency pause", async () => {
        // generate an anonymous account
        const anonymous = Keypair.generate();

        // Airdrop SOLs to the anonymous account.
        await provider.connection.confirmTransaction(
            await provider.connection.requestAirdrop(anonymous.publicKey, 1e10),
            "confirmed"
        );

        // it should reject for anonymous users to update emergency pause
        await assert.rejects(
            async () => {
                await program.rpc.pause(true, {
                    accounts: {
                        state: referralPda,
                        partnerAccount: anonymous.publicKey,
                    },
                    signers: [anonymous],
                });
            },
            {
                // TODO: revamp error messages
                message: "65440: FFA0 Unexpected account",
            }
        );
    });
});
